[package]
name = "model"
description = "norlys.live model"
repository = "https://github.com/norlys-org/model"
version = "0.25.4"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [".", "protobufs/build"]

[dependencies]
protobufs = { path = "./protobufs/build" }
console_error_panic_hook = "0.1.7"
nalgebra = "0.33.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
prost = "0.13.5"
