name: Archive data fetching

on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TGO_PASSWORD: ${{ secrets.TGO_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_READ_TOKEN }}
        submodules: true  # Ensure submodules are checked out
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python retrieve_archive.py

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add data/month
        git commit -m "Daily data retrieval"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
